### ISSUE TITLE
LanguageToolR installation issue

### ISSUE THREAD

**Issue by TinaSarkar** [alapo/Literate-Programming#16]
If I type into my consol: 

`install.packages("LanguageToolR")`

I get the message: 

> Warning in install.packages :
> package ‘LanguageToolR’ is not available for this version of R
> 
> A version of this package for your version of R might be available elsewhere,
> see the ideas at
> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

When I tried to look on cran I couldn't find LanguageTools. Does anyone know where I could find a version that will work for me?

Thank you!

**Comment by alapo** [comment]
Hey Tina,

If you stick around after the workshop today I'll help ya fix the issue.

Andrew

**Comment by alapo** [comment]
Email invite sent!

**Comment by alapo** [comment]
Issue was resolved over a Zoom call. Uploading to YouTube now. Seems to be a timeout error related to the zip file. May be worth posting an issue on the `LanguageR` github repo.
