### ISSUE TITLE
Error in import("raw/data.xlsx", which = "MRI-data") :   could not find function "import"

### ISSUE THREAD

**Issue by Danika4321** [alapo/Literate-Programming#19]
Hello,

Im doing module 7 right now and im having trouble running lines 70-80. I keep getting the error from line 76-80: Error in import("raw/data.xlsx", which = "MRI-data") : could not find function "import".
 I made sure I have the data.xlsx in my raw folder and can see the MRI-data section. I also looked up the error but couldn't find a solution there. I was able to run the first portion of the lines fine, but when I added the second portion it caused the error. Im not sure what the issue is, could it be related to the file itself?

Thanks!

```{r load, echo=FALSE, eval=TRUE}
# Load your data ----------
df.demo <- rio::import("raw/data.xlsx", which = "demographics") %>% # Imports the sheet with demographic data
  janitor::clean_names() %>% # Clean the column names
  dplyr::rename(
    "ID" = "study_id",
    "Group" = "group"
  )

df.mri <- import("raw/data.xlsx", which = "MRI-data") %>%
  janitor::clean_names() %>%                             # clean column names
  janitor::remove_empty(c("rows", "cols")) %>%           # remove the empty rows and columns
  janitor::remove_constant(na.rm = TRUE, quiet = FALSE)  # remove the column of all "Yes" values 
```

**Comment by alapo** [comment]
Hey Danika, 

Are you "knitting" the document or clicking on the small play button within the RMD?

**Comment by Danika4321** [comment]
Im pressing the play button for that selected code chunk so that the df.mri can appear in my data environment (but it doesn't because of the error). It's the part at 25:40 of module 7 if that helps.

**Comment by alapo** [comment]
Try knitting the whole document. You can't run just one chunk in the middle of the document, you also need to run the chunks before it. Which loads and/or installs the packages. If this fails, bring your laptop with you tomorrow.
