### ISSUE TITLE
Errors while running unchanged code Mod7

### ISSUE THREAD

**Issue by Danika4321** [alapo/Literate-Programming#20]
Hello,

Im having trouble running this line of code from module 7:

`df.mri <- df.mri %>%
        dplyr::rename(
          # "NewName" = "OldName"
          "completed_mri" ="completed_mri_1_yes_0_no") %>%
        filter(site_mri == "Calgary" & completed_mri == "1") %>%         # remove all data that is not from Calgary and those who did not complete an MRI
        filter(id %in% unique(df.demo$ID)) %>%                           # I only want IDs that are in present in df.demo
        suppressWarnings(hablar::convert(num(left_af:right_uf))) %>% # Converts some of the columns into numeric -- requires hablar library
        gather(mriloc, dti_value, left_cst:right_uf) %>%
        dplyr::arrange(id) %>%
        mutate(hemisphere = case_when(
          str_contains(mriloc, "left") == TRUE ~ "Left",
          str_contains(mriloc, "left") == FALSE ~ "Right"
        ))`

Its the exact same code as you have in the video and im able to knit the document but when I try to run the chunk itself (after having run all the lines before without issue) I get the following error:   

Error in `dplyr::rename()`:
! Can't rename columns that don't exist.
✖ Column `completed_mri_1_yes_0_no` doesn't exist.
Backtrace:
  1. ... %>% ...
 10. dplyr:::rename.data.frame(., completed_mri = "completed_mri_1_yes_0_no")
Error in dplyr::rename(., completed_mri = "completed_mri_1_yes_0_no")

In the video there's an issue with this line but the steps to remove it are already done to the code so I don't think it's the same issue. I believe we changed the name of the MRI column previously in the module so could that be the reason behind the error? Im getting some errors while running lines after this one so im not sure if these are related. 

Thanks for your help!

Danika

**Comment by alapo** [comment]
That is strange. Are you able to do a screen recording of the issue? If I remember correctly, you are using a Mac computer. If that is the case, it is very easy to do, please see [here](https://support.apple.com/en-ca/102618). 

If the document is knitting properly, and you are only getting errors when you run the chunks...I would not be too concerned. Just continue with the rest of the modules. If I can't figure out the issue from the video you upload, then we can schedule a zoom meeting to go over it.

**Comment by Danika4321** [comment]
It's not letting me add a video because it's too big (about a minute long) but I can send it to your email. I have finished the modules this is just an issue I encountered but kept going.

**Comment by alapo** [comment]
Upload it to youtube give me the link

**Comment by Danika4321** [comment]
https://www.youtube.com/watch?v=OkPT0jl62Qs

**Comment by alapo** [comment]
Ok yes that was just an example I had for in the tutorial. "rowname" is telling you to "please insert rowname here".
