### ISSUE TITLE
Downloading easystats suite fails

### ISSUE THREAD

**Issue by Psmitty4** [alapo/Literate-Programming#4]
**Describe the bug**
When attempting to download the easystats suite the download fails and produces the following error. 

```
"Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/easystats/easystats/tarball/HEAD' failed" 
```

**To Reproduce**
I followed the correct steps in the installation video with the only difference being I had to generate a PAT for GitHub as there was no login prompt for Mac. 

**Expected behavior**
I expected the download to work perfectly as in the video.

**Screenshots**
N/A

**sessionInfo()**
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] zip_2.1.1         Rcpp_1.0.6        cellranger_1.1.0  pillar_1.5.0      compiler_4.0.4    prettyunits_1.1.1 forcats_0.5.1     remotes_2.2.0    
 [9] sys_3.4           tools_4.0.4       testthat_3.0.2    pkgbuild_1.2.0    pkgload_1.2.0     jsonlite_1.7.2    tibble_3.1.0      memoise_2.0.0    
[17] lifecycle_1.0.0   pkgconfig_2.0.3   rlang_0.4.10      openxlsx_4.2.3    cli_2.3.1         curl_4.3          haven_2.3.1       rio_0.5.26       
[25] fastmap_1.1.0     withr_2.4.1       hms_1.0.0         desc_1.2.0        fs_1.5.0          vctrs_0.3.6       askpass_1.1       devtools_2.3.2   
[33] rprojroot_2.0.2   glue_1.4.2        data.table_1.14.0 R6_2.5.0          processx_3.4.5    fansi_0.4.2       readxl_1.3.1      foreign_0.8-81   
[41] pacman_0.5.1      sessioninfo_1.1.1 rscodeio_0.1.0    callr_3.5.1       purrr_0.3.4       magrittr_2.0.1    ps_1.6.0          credentials_1.3.0
[49] ellipsis_0.3.1    usethis_2.0.1     assertthat_0.2.1  utf8_1.1.4        stringi_1.5.3     openssl_1.4.3     cachem_1.0.4      crayon_1.4.1   
```
**Additional context**
Tried to install from source, also did not work and produced the following error: 

```
Error: package or namespace load failed for ‘easystats’:
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: NULL
  error: 'color_theme' is not an exported object from 'namespace:insight'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/parkersmith/Library/R/4.0/library/easystats’
```

**Comment by alapo** [comment]
Hey Parker,

I am unable to troubleshoot Mac problems. Can you hop onto the class Zoom? I can help you troubleshoot there.

Thanks,
Andrew

**Comment by chazdm** [comment]
Hi! I am also having troubles with installing the easystats package. The error message I get is as below. I got the same message when I tried to install from source.

Error: Failed to install 'easystats' from GitHub:
  (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.0:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.0/PACKAGES'

**Comment by alapo** [comment]
chazdm please provide `devtools::session_info()` in the future. I can hop on the class Zoom to help

**Comment by alapo** [comment]
> Hi! I am also having troubles with installing the easystats package. The error message I get is as below. I got the same message when I tried to install from source.
> 
> Error: Failed to install 'easystats' from GitHub:
> (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.0:
> cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.0/PACKAGES'

@chazdm please provide `devtools::session_info()` in the future. 

I will hop on the class Zoom now if you'd like some help troubleshooting

**Comment by chazdm** [comment]
Thanks Andrew. I am available to connect on zoom now.

**Comment by alapo** [comment]
> Thanks Andrew. I am available to connect on zoom now.

Come join the party

**Comment by alapo** [comment]
If anyone else is having an issue with installing `easystats` go ahead and replace the following line 
```r
remotes::install_github("easystats/easystats") # installs the whole easystats suite

```

and run these lines instead

```r
install.packages(c("insight", "bayestestR", "parameters", "performance", "effectsize", "correlation", "modelbased))
```

**Comment by chazdm** [comment]
Ok that worked.

Thanks Andrew!

________________________________

**Comment by strengejacke** [comment]
FWIW, I think the problem is related to the _report_ package not being on CRAN. This here _should_ work:

1. `install.packages(c("insight", "bayestestR", "parameters", "performance", "effectsize", "correlation", "modelbased", "see"))` # note the _see_ pkg
2. `remotes::install_github("easystats/report")`
3. `remotes::install_github("easystats/easystats")`

**Comment by alapo** [comment]
> FWIW, I think the problem is related to the _report_ package not being on CRAN. This here _should_ work:
> 
> 1. `install.packages(c("insight", "bayestestR", "parameters", "performance", "effectsize", "correlation", "modelbased", "see"))` # note the _see_ pkg
> 2. `remotes::install_github("easystats/report")`
> 3. `remotes::install_github("easystats/easystats")`

Just for anyone wondering why I was preaching the R Community during our second workshop...We collectively ran into an issue and no less than 10 minutes after I posted an issue on GitHub...one of the creators of the `easystats` package helps us out!!

Amazing!!!
