### ISSUE TITLE
Where can we download the "MyProjectName.Rproj" file?

### ISSUE THREAD

**Issue by chelseachristie** [alapo/Literate-Programming#5]
Hi there,

I followed along with the "Workshop 03 - Installation" YouTube video up until minute 8:20 where Andrew opens up the "MyProjectName.Rproj" file. Were we sent that file previously? Or can we download this file from GitHub? If so, how? I can open that folder, but it just shows me all the individual files... 

Please help!

-Chelsea

**Comment by alapo** [comment]
Hi Chelsea,

If you go to the main page of the GitHub page. You can click on 

![](https://i.imgur.com/hh22KWC.png)
