### ISSUE TITLE
API limit exceeded

### ISSUE THREAD

**Issue by nicoleracine** [alapo/Literate-Programming#8]
**Describe the bug**
While trying to install the different packages in the Install.R file, I ran into the following error:

**To Reproduce**
When trying to run the code that requires Github, something went wrong with the token. I ran this code:

```
remotes::install_github("easystats/easystats")
remotes::install_github("easystats/report")  # You only need to do that once
remotes::install_github("easystats/correlation")
remotes::install_github("davidgohel/officedown")

devtools::install_github('achetverikov/apastats', subdir='apastats')
devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
devtools::install_github('rstudio/rmarkdown')

```
I got this error:
Error: Failed to install 'rmarkdown' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 172.103.181.16. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2021-03-23 18:10:44 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
> usethis::browse_github_pat()
Error: `browse_github_pat()` was deprecated in usethis 2.0.0 and is now defunct.
Please use `create_github_token()` instead.
> create_github_token()
Error in create_github_token() : 
  could not find function "create_github_token"
> 

**Expected behavior**
In the video Adam showed, he got prompted to sign into github and that never happened for me, which is why I might be getting this error. 

**Screenshots**
see attached

**devtools::session_info()**
In your Console, type `devtools::session_info()` and paste it in the code section below. This allows me to evaluate your R environment for any issues.

<details>
<summary>

</summary>
<p>

```r
# REMOVE THIS LINE AND PASTE OUTPUT FROM 
 Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Denver              
 date     2021-03-23                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source                                
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.4)                        
 cachem        1.0.4   2021-02-13 [1] CRAN (R 4.0.4)                        
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.4)                        
 cellranger    1.1.0   2016-07-27 [1] CRAN (R 4.0.4)                        
 cli           2.3.1   2021-02-23 [1] CRAN (R 4.0.4)                        
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.4)                        
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.4)                        
 data.table    1.14.0  2021-02-21 [1] CRAN (R 4.0.4)                        
 desc          1.3.0   2021-03-05 [1] CRAN (R 4.0.4)                        
 devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.4)                        
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.4)                        
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.4)                        
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.4)                        
 fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.4)                        
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.4)                        
 forcats       0.5.1   2021-01-27 [1] CRAN (R 4.0.4)                        
 foreign       0.8-81  2020-12-22 [2] CRAN (R 4.0.4)                        
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.4)                        
 gdtools       0.2.3   2021-01-06 [1] CRAN (R 4.0.4)                        
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.4)                        
 haven         2.3.1   2020-06-01 [1] CRAN (R 4.0.4)                        
 hms           1.0.0   2021-01-13 [1] CRAN (R 4.0.4)                        
 htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.4)                        
 knitr         1.31    2021-01-27 [1] CRAN (R 4.0.4)                        
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)                        
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.4)                        
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.0.4)                        
 officedown    0.2.1   2021-02-01 [1] CRAN (R 4.0.4)                        
 officer       0.3.17  2021-03-05 [1] CRAN (R 4.0.4)                        
 openxlsx      4.2.3   2020-10-27 [1] CRAN (R 4.0.4)                        
 pacman        0.5.1   2019-03-11 [1] CRAN (R 4.0.4)                        
 pillar        1.5.1   2021-03-05 [1] CRAN (R 4.0.4)                        
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.4)                        
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.4)                        
 pkgload       1.2.0   2021-02-23 [1] CRAN (R 4.0.4)                        
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.4)                        
 processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.4)                        
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.0.4)                        
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.4)                        
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.4)                        
 Rcpp          1.0.6   2021-01-15 [1] CRAN (R 4.0.4)                        
 readxl        1.3.1   2019-03-13 [1] CRAN (R 4.0.4)                        
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.4)                        
 rio           0.5.26  2021-03-01 [1] CRAN (R 4.0.4)                        
 rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.4)                        
 rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.4)                        
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.4)                        
 rscodeio      0.1.0   2021-03-19 [1] Github (anthonynorth/rscodeio@88a1a37)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.4)                        
 rvg           0.2.5   2020-06-30 [1] CRAN (R 4.0.4)                        
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.4)                        
 stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.3)                        
 systemfonts   1.0.1   2021-02-09 [1] CRAN (R 4.0.4)                        
 testthat      3.0.2   2021-02-14 [1] CRAN (R 4.0.4)                        
 tibble        3.1.0   2021-02-25 [1] CRAN (R 4.0.4)                        
 usethis       2.0.1   2021-02-10 [1] CRAN (R 4.0.4)                        
 utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.4)                        
 uuid          0.1-4   2020-02-26 [1] CRAN (R 4.0.3)                        
 vctrs         0.3.6   2020-12-17 [1] CRAN (R 4.0.4)                        
 withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.4)                        
 xfun          0.22    2021-03-11 [1] CRAN (R 4.0.4)                        
 xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.4)                        
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.3)                        
 zip           2.1.1   2020-08-27 [1] CRAN (R 4.0.4)                        

[1] C:/Users/racin/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.4/library
> 



**Additional context**
Add any other context about the problem here.
![Capture](https://user-images.githubusercontent.com/80359264/112193223-4d843a80-8bcd-11eb-99db-3639aeabd493.PNG)

**Comment by alapo** [comment]
Hi Nicole. We won't have time to troubleshoot this before the workshop starts in 8 minutes. But can you confirm that you have created a GitHub account? If so which browser are you using by default?

**Comment by alapo** [comment]
Its no worries. I doubt the videos I am uploading will fix your issue so I would suggest hopping onto the zoom now if you are available. Otherwise we can schedule a time

**Comment by alapo** [comment]
Hi Nicole, 

Just following up on this. Please shoot me an email with times.  You can also try running this line of code


```r
credentials::git_credential_ask("https://github.com")

```

**Comment by nicoleracine** [comment]
Hi Andrew,

Apologies for the delayed reply. I tried running the line that you send and it did prompt me to login to github but the error I am having with tinytex remains. When I run the line to confirm it fails.
Do you have any time tomorrow morning before webinar to zoom?

Thanks for your help with this,

Nicole

Nicole Racine, Ph.D., R.Psych. (she/her)
Post-doctoral Research Fellow
University of Calgary
2500 University Drive NW
Calgary, Alberta, T2N 1N4
Phone:403-992-7869
Twitter: @racinen2
I respectfully acknowledge that I work and live on the territory of the Blackfoot and the people of the Treaty 7 region in Southern Alberta, which includes the Siksika, the Piikani, the Kainai, the Tsuut’ina and the Stoney Nakoda First Nations, including Chiniki, Bearspaw, and Wesley First Nation. The City of Calgary is also home to Métis Nation of Alberta, Region III.



From: Nicole Racine ***@***.***>
Date: Monday, March 29, 2021 at 3:43 PM
To: alapo/Literate-Programming ***@***.***>, alapo/Literate-Programming ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

From: Nicole Racine ***@***.***>
Date: Tuesday, March 23, 2021 at 1:09 PM
To: alapo/Literate-Programming ***@***.***>, alapo/Literate-Programming ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

Hi Andrew (sorry for calling you adam),

No problem, I’m going to follow along on the videos you are posting.
I have created a github account and google chrome is my default web-browser. I have been running this on my PC, I also have a mac, so could try running it on there and see what happens.

Thanks for the help and I hope I didn’t fail the “posting an issue” too terribly.

Nicole



From: alapo ***@***.***>
Reply-To: alapo/Literate-Programming ***@***.***>
Date: Tuesday, March 23, 2021 at 12:53 PM
To: alapo/Literate-Programming ***@***.***>
Cc: Nicole Racine ***@***.***>, Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

[△EXTERNAL]


Hi Nicole. We won't have time to troubleshoot this before the workshop starts in 8 minutes. But can you confirm that you have created a GitHub account? If so which browser are you using by default?

**Comment by nicoleracine** [comment]
Ps. I went through the debugging recommendations but no luck.

Nicole Racine, Ph.D., R.Psych. (she/her)
Post-doctoral Research Fellow
University of Calgary
2500 University Drive NW
Calgary, Alberta, T2N 1N4
Phone:403-992-7869
Twitter: @racinen2
I respectfully acknowledge that I work and live on the territory of the Blackfoot and the people of the Treaty 7 region in Southern Alberta, which includes the Siksika, the Piikani, the Kainai, the Tsuut’ina and the Stoney Nakoda First Nations, including Chiniki, Bearspaw, and Wesley First Nation. The City of Calgary is also home to Métis Nation of Alberta, Region III.



From: Nicole Racine ***@***.***>
Date: Monday, March 29, 2021 at 3:57 PM
To: alapo/Literate-Programming ***@***.***>, alapo/Literate-Programming ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

Hi Andrew,

Apologies for the delayed reply. I tried running the line that you send and it did prompt me to login to github but the error I am having with tinytex remains. When I run the line to confirm it fails.
Do you have any time tomorrow morning before webinar to zoom?

Thanks for your help with this,

Nicole

Nicole Racine, Ph.D., R.Psych. (she/her)
Post-doctoral Research Fellow
University of Calgary
2500 University Drive NW
Calgary, Alberta, T2N 1N4
Phone:403-992-7869
Twitter: @racinen2
I respectfully acknowledge that I work and live on the territory of the Blackfoot and the people of the Treaty 7 region in Southern Alberta, which includes the Siksika, the Piikani, the Kainai, the Tsuut’ina and the Stoney Nakoda First Nations, including Chiniki, Bearspaw, and Wesley First Nation. The City of Calgary is also home to Métis Nation of Alberta, Region III.



From: Nicole Racine ***@***.***>
Date: Monday, March 29, 2021 at 3:43 PM
To: alapo/Literate-Programming ***@***.***>, alapo/Literate-Programming ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

From: Nicole Racine ***@***.***>
Date: Tuesday, March 23, 2021 at 1:09 PM
To: alapo/Literate-Programming ***@***.***>, alapo/Literate-Programming ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

Hi Andrew (sorry for calling you adam),

No problem, I’m going to follow along on the videos you are posting.
I have created a github account and google chrome is my default web-browser. I have been running this on my PC, I also have a mac, so could try running it on there and see what happens.

Thanks for the help and I hope I didn’t fail the “posting an issue” too terribly.

Nicole



From: alapo ***@***.***>
Reply-To: alapo/Literate-Programming ***@***.***>
Date: Tuesday, March 23, 2021 at 12:53 PM
To: alapo/Literate-Programming ***@***.***>
Cc: Nicole Racine ***@***.***>, Author ***@***.***>
Subject: Re: [alapo/Literate-Programming] Series of Errors Using Install.R (#8)

[△EXTERNAL]


Hi Nicole. We won't have time to troubleshoot this before the workshop starts in 8 minutes. But can you confirm that you have created a GitHub account? If so which browser are you using by default?

**Comment by alapo** [comment]
Just sent you an email

**Comment by alapo** [comment]
Fixed over a Zoom call. Issue was related to not running the installation lines after fixing the GitHub authentication issue.
